---
driver:
  name: azurerm
  azure_resource_group_prefix: kitchen-<%= ENV['USER'] %>-
  resource_group_tags: &tags
    X-Contact: <%= ENV['USER'] %>
    X-Application: <%= ENV['X_APPLICATION'] %>
    X-Dept: <%= ENV['X_DEPT'] %>
    X-Customer: "Test-Kitchen"
    X-Project: "Test-Kitchen"
    X-TTL: 6
  vm_tags: *tags

driver_config:
  # put real subscription_id path in .kitchen.local.yml
  # subscription_id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  location: "Central US"
  machine_size: "Standard_DS2_v2"

# put real ssh_key path in .kitchen.local.yml
#transport:
#  ssh_key: /Users/user/.ssh/id_rsa

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: win19
    driver:
      image_urn: MicrosoftWindowsServer:WindowsServer:2019-Datacenter:latest
  - name: ubuntu-1804
    driver:
      image_urn: Canonical:UbuntuServer:18.04-LTS:latest
  - name: centos-75
    driver:
      image_urn: OpenLogic:CentOS:7.5:latest

suites:
  - name: apt-repo
    driver:
      os_disk_size_gb: 300
    excludes: win19, centos-75
    run_list:
      - recipe[patch_management::apt_repo]
  - name: yum-repo
    excludes: win19, ubuntu-1804
    run_list:
      - recipe[patch_management::yum_repo]
  - name: wsus
    excludes: centos-75, ubuntu-1804
    run_list:
      - recipe[patch_management::wsus_server]
    driver_config:
      machine_size: "Standard_DS4_v2"
  - name: centos
    excludes: win19, ubuntu-1804
    run_list:
      - recipe[patch_management::centos_client]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/linux-patch-benchmark
  - name: ubuntu
    excludes: win19, centos-75
    run_list:
      - recipe[patch_management::ubuntu_client]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/linux-patch-benchmark
  - name: windows
    excludes: centos-75, ubuntu-1804
    run_list:
      - recipe[patch_management::windows_client]
    verifier:
      inspec_tests:
        - https://github.com/dev-sec/windows-patch-benchmark
