name 'patch_management'
maintainer 'Chef Software, Inc'
maintainer_email 'success@chef.io'
license 'apachev2'
description 'Installs/Configures patch_management'
long_description 'Installs/Configures patch_management'
version '0.1.1'

depends 'wsus-client'
depends 'wsus-server'
depends 'yum'
